# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-26 23:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, 'Alias must be at least 2 characters.')]),
        ),
    ]
